### ISSUE TITLE
Definir a dónde apunta RSS

### ISSUE THREAD

**Issue by fernandouval** [datauy/quesabes-theme#1]
Suscribirse a RSS o en su defecto al newsletter en front-page

**Comment by alfonsocora** [comment]
Esto ya lo agregó @picandocodigo al migrar: https://github.com/datauy/quesabes-theme/blob/master/lib/views/layouts/default.html.erb#L41
El ícono no aparece en algunos browsers nuevos, como Chrome porque sacaron el soporte para RSS.
